version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-loja
    environment:
      SA_PASSWORD: "Asdf1234!@#A"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  identityserver:
    build:
      context: .
      dockerfile: LojaManoel.IdentityServer/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000

  loja-api:
    build:
      context: ./LojaManoel.API
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - identityserver
      - sqlserver

volumes:
  sqlserver_data: